### ISSUE TITLE
Whisper Notifications

### ISSUE THREAD

**Issue by DoctorWigglez** [CBenni/mt2#23]
For moderation, I would prefer that whisper notifications change either the color of the whispers tab to red, or even a notification icon on the whispers tab with how many whispers are unread like this: ![](https://i.imgur.com/AdW8mEc.png)

The current implementation of a toast is not ideal as it pops up in some way on the screen and impairs vision in some way.

**Comment by arkham81a** [comment]
And for a non moderation perspective I would say popups are great! If you're not a streamer. There needs to be an option to disable them and have options to display what Wiggles suggested above as an alternative. If you're a streamer that popup needs to have a disable setting otherwise you're not gonna use MT2. (Although me myself I'm a fan of the popups as they are, pls don't remove them completely)

**Comment by CBenni** [comment]
The tab notifications will happen eventually, Its not quite as easy as you might think however. 
As for disabling popups, you could just do that with CSS once I fix custom stylesheets, I cant add an option for everything.

**Comment by CBenni** [comment]
Fixed in https://github.com/CBenni/mt2/commit/bb57f95c018302cba176b022e3351d2395cfcfed
